"""Build and read back a real companion MPQ with a locally built Unicode StormLib.

Usage: python pack-companion.py STORMLIB_DLL ASSET_DIR OUTPUT_MPQ HASH_HEADER
StormLib is build tooling only; it is not linked into or shipped with the plugin.
"""
import ctypes as c
import hashlib
import json
from pathlib import Path
import sys

storm_path, source, output, header = map(Path, sys.argv[1:])
storm = c.WinDLL(str(storm_path.resolve()), use_last_error=True)
H, U, P = c.c_void_p, c.c_uint32, c.POINTER(c.c_void_p)
def bind(name, args, result=c.c_bool):
    fn = getattr(storm, name)
    fn.argtypes, fn.restype = args, result
    return fn
create = bind('SFileCreateArchive', [c.c_wchar_p, U, U, P])
create_file = bind('SFileCreateFile', [H, c.c_char_p, c.c_uint64, U, U, U, P])
write = bind('SFileWriteFile', [H, H, U, U])
finish = bind('SFileFinishFile', [H])
close = bind('SFileCloseArchive', [H])
open_archive = bind('SFileOpenArchive', [c.c_wchar_p, U, U, P])
open_file = bind('SFileOpenFileEx', [H, c.c_char_p, U, P])
read = bind('SFileReadFile', [H, H, U, c.POINTER(U), H])
size = bind('SFileGetFileSize', [H, c.POINTER(U)], U)
close_file = bind('SFileCloseFile', [H])
def check(ok):
    if not ok:
        raise OSError(c.get_last_error(), 'StormLib operation failed')

manifest = json.loads((source / 'manifest.json').read_text())
entries = manifest['entries']
assert len(entries) == 4
assert all(e['path'].startswith('data/hd/global/ui/d2rloader/ruffneckk-vendor-stock-refresh/') for e in entries)
assert len(set(e['path'] for e in entries)) == len(entries)
if output.exists():
    raise FileExistsError(output)  # Preserve previously paired artifacts.
output.parent.mkdir(parents=True, exist_ok=True)
archive = H()
check(create(str(output.resolve()), 0x00100000, 16, c.byref(archive)))
try:
    for entry in entries:
        data = (source / entry['path']).read_bytes()
        assert hashlib.sha256(data).hexdigest() == entry['sha256']
        file = H()
        # Preserve SDK-normalized virtual paths in the MPQ directory/listfile.
        # Matching only a backslash lookup does not validate the Loader's
        # forward-slash virtual resource lookup.
        check(create_file(archive, entry['path'].encode('ascii'), 0, len(data), 0, 0x200, c.byref(file)))
        check(write(file, data, len(data), 2))
        check(finish(file))
finally:
    check(close(archive))
check(open_archive(str(output.resolve()), 0, 0x100, c.byref(archive)))
try:
    listing = H()
    check(open_file(archive, b'(listfile)', 0, c.byref(listing)))
    try:
        listing_size = size(listing, None)
        listing_bytes = c.create_string_buffer(listing_size)
        listing_count = U()
        check(read(listing, listing_bytes, listing_size, c.byref(listing_count), None))
        assert listing_count.value == listing_size
        paths = set(listing_bytes.raw.decode('ascii').splitlines()) - {''}
        assert paths == {entry['path'] for entry in entries}, paths
        assert all('\\' not in path for path in paths)
    finally:
        check(close_file(listing))
    for entry in entries:
        file = H()
        check(open_file(archive, entry['path'].encode('ascii'), 0, c.byref(file)))
        try:
            assert size(file, None) == entry['bytes']
            buffer = c.create_string_buffer(entry['bytes'])
            count = U()
            check(read(file, buffer, len(buffer), c.byref(count), None))
            assert count.value == len(buffer)
            assert hashlib.sha256(buffer.raw).hexdigest() == entry['sha256']
        finally:
            check(close_file(file))
finally:
    check(close(archive))
digest = hashlib.sha256(output.read_bytes()).digest()
header.write_text('// Generated by tools/pack-companion.py; pairs the DLL with this exact MPQ.\n'
                  '#pragma once\n#include <array>\n#include <cstdint>\n'
                  'namespace RuffnecKk::VendorStockRefresh {\n'
                  'inline constexpr std::array<std::uint8_t, 32> CompanionSha256{\n    '
                  + ', '.join(f'0x{b:02X}' for b in digest) + '\n};\n}\n')
manifest['archive'] = {'filename': output.name, 'bytes': output.stat().st_size, 'sha256': digest.hex(), 'readbackVerified': True}
output.with_suffix('.manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
print(json.dumps(manifest['archive']))
